services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    env_file:
      - ./db/.env
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    ports:
      - "8000:8080"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
