version: '3.7'

services:
  db:
    build: ./db
    container_name: db
    restart: always
    env_file:
      - ./db/.env

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db