version: '3.7'

services:
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    env_file:
      - ./db/.env
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d:z

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
